# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'need_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_need_file_dlg(object):
    def setupUi(self, need_file_dlg):
        need_file_dlg.setObjectName("need_file_dlg")
        need_file_dlg.resize(391, 106)
        self.verticalLayout = QtWidgets.QVBoxLayout(need_file_dlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(need_file_dlg)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.part_cb = QtWidgets.QComboBox(need_file_dlg)
        self.part_cb.setObjectName("part_cb")
        self.part_cb.addItem("")
        self.part_cb.addItem("")
        self.part_cb.addItem("")
        self.part_cb.addItem("")
        self.horizontalLayout.addWidget(self.part_cb)
        self.number_cb = QtWidgets.QComboBox(need_file_dlg)
        self.number_cb.setObjectName("number_cb")
        self.number_cb.addItem("")
        self.number_cb.addItem("")
        self.number_cb.addItem("")
        self.number_cb.addItem("")
        self.number_cb.addItem("")
        self.number_cb.addItem("")
        self.number_cb.addItem("")
        self.horizontalLayout.addWidget(self.number_cb)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(need_file_dlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(need_file_dlg)
        self.buttonBox.accepted.connect(need_file_dlg.accept) # type: ignore
        self.buttonBox.rejected.connect(need_file_dlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(need_file_dlg)

    def retranslateUi(self, need_file_dlg):
        _translate = QtCore.QCoreApplication.translate
        need_file_dlg.setWindowTitle(_translate("need_file_dlg", "Для запуска программы требуется файл"))
        self.label.setText(_translate("need_file_dlg", "Выберите сложность и номер задачи"))
        self.part_cb.setItemText(0, _translate("need_file_dlg", "beta"))
        self.part_cb.setItemText(1, _translate("need_file_dlg", "easy"))
        self.part_cb.setItemText(2, _translate("need_file_dlg", "normal"))
        self.part_cb.setItemText(3, _translate("need_file_dlg", "hard"))
        self.number_cb.setItemText(0, _translate("need_file_dlg", "9"))
        self.number_cb.setItemText(1, _translate("need_file_dlg", "17"))
        self.number_cb.setItemText(2, _translate("need_file_dlg", "22"))
        self.number_cb.setItemText(3, _translate("need_file_dlg", "24"))
        self.number_cb.setItemText(4, _translate("need_file_dlg", "26"))
        self.number_cb.setItemText(5, _translate("need_file_dlg", "27_A"))
        self.number_cb.setItemText(6, _translate("need_file_dlg", "27_B"))
